version: '3.7'

services: 
  postgreSQL:
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=FacilitaDB
    
    networks:
      - postgres-compose-network

  pgadmin4:
    image: dpage/pgadmin4
    container_name: "pgadmin-facilita"
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: root@email.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports: 
      - "9090:80"
    depends_on: 
      - postgreSQL
    networks: 
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge